---
- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "clement.patout@gmail.com"
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Cl√©ment Patout"
